---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-introduction"
      label: "Introduction"
      solveButton: false

tabs:
  - name: "Satellite Web UI"
    url: https://satellite-${guid}.${domain}/
    external: true
  - name: "satellite.lab terminal"
    url: /wetty_satellite/ssh/root
  - name: "rhel1.lab terminal"
    url: /wetty_rhel1/ssh/root
  - name: "rhel2.lab terminal"
    url: /wetty_rhel2/ssh/root
  - name: "rhel-ai.lab terminal"
    url: /wetty_rhel-ai/ssh/root
  - name: "rhel-ai.lab Web GUI"
    url: https://opencode-${guid}.${domain}/
    external: true

